# Generated by Django 4.1.1 on 2022-12-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_notes', '0003_topic_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Note',
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name_plural': 'notes'},
        ),
    ]
